language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - sshpass
cache:
  directories:
  - "$HOME/.ivy2/cache"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
after_success:
- if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]];
  then cd ..; fi
- if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]];
  then ls; fi
- if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]];
  then tar -czf package.tgz rest-interface; fi
- if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]];
  then export SSHPASS=$DEPLOY_PASS; fi
- if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]];
  then sshpass -e scp -P 15003 -o stricthostkeychecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH;
  fi
- if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]];
  then sshpass -e ssh -p 15003 $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh; fi
- if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]];
  then rm -rf package.tgz; fi
env:
  global:
  - secure: dl0fY/o4QI7K2J3QtMDZ2nKoksWA5PdPajFQBziTbWZ4CEwTMUIu05F32qE0+AXYLwcapp4/ODgzfb3SEY0n9NGxXyNj54MsfFgWgWQsEJRoDU9yTWOScFpEQt43bD+8U8OozJV/ZAtiGMKB+fq03cXuwWIKPkhqOoCvRcnfaKyB+PPWMrUtQm0pkn8Mx51zmqAtML1HpnWUhGqjkQI/67QXq3/Vpcmpl0TYpvt071VV3PZCm2QXxOHOpE7vRP49U+/xd/JIpV1MEmC9rEvoPmTEVkRMe6vodTJi1nfPwkVcCnEy+OWhNrBWAPzfgXfXutVx+UkuleUKe85jGh8PcLcIJ6uc2SiHjrvMZCVZ9mdOB0DI9g0l0xKqOCH67f3P/GGf7Fmf5lRS5vj9FmX3FyMNT9E7EnDyImwbLxaZK2s6fh7b37thQQvZqRGsjx09qpMRZCdCF9DgaWc8dAclqFgwboooGaKjvGPkdgMTkv03PHpz4htF2jst9Su86GCkQoUOGSA/odSrxUIepkP59O41N2aGMfO5anicrKh+7/jp4NzliHYFCtSCiSBcSkYunkOiPE2/CbjLQ9CD66veXUTvgjf6SQFQvZsvWur6VQA84GTTqpLBYVKMKzDxF+R4/R4sdlN2HtzjG30X8g797+29wJsnM2AzeL2JbJPfUSU=
  - secure: YEYakXGkWcsRj/M7RgwvWHzRJ8MNJBffqEaPsHxj6Ld/36KxJ6J1iq6XFe+rENHlev/7iLAij9WDxAbjooEM9N/yLiE+Mli99bO3aP1UMZRXGFBU7IcH+FSD8UajxYsb1rrDAXCTxnrzsgw2cZFYO11WpKf83M2ewWcPUmJjMPGvP+iZnCBlUwPnEvWOAEkdeX3Tvl7MpM/o6FtWvHtwr5EQSbBpBbxqWAMd7e1Z9JKFcJOMne4wfAvknzoClJ3+7lXMwP3cuGhOkKzP8pkGsFkssaj81gXZTyz9HvHnMjC6Y/Is5JShMHf7fH4YtKcmz22ax8QahxZXVPuAhWtJ8YH+O7FjF5MKm4b+Mj754rlDEGeIXaQWUMhNaxEV2/ukxAuC8Up+o2QXJg81wOze3UmNCt9+GwZMBpcJQkNLuhx9Q98BpVOIoipK3HDUcMfyOS4jqwSKNVHU2kdNQjr+MiOXDV/oAzY6ZjSzPA/XR0bEcBPvuosVh37t7ntQP1l/o0pDcLtcpU5Qa63ffho/FVQKR0ViIPOP5FvMxV1Cx2QQFVLEYPTpg6LMx93m6ecAfJ6eJ7cnq/DMxNo78/dea0Y33SipfEhXmK0pVOhPtzUFNUEKtzo1WV6bulSoNBpZ0dI9D6LjZsK4TKVlTDmaa52eQcN0h8J4irp/ukALVSw=
  - secure: ASI1PdBu9lXSIcHrQ+pru+nHDZgrWgKl9WtQyVKDY0f5GMt/H/mVuQWAE+3mKzqbNI3GNl1DCqzHbtUYSgozT0hvr2JHh9vNXHaOS3zmVug7hckf7bjoI03aKL6YR4HxwprPHNLqSV9f6V4XF87x2xmeCuT7FPFIQ+FGmrtkCF6QKHLe86vGk8kH9l6CFM+kkoFbRuzK1ZYZJQq0OQUO7L9oHLIsxyFV8dPa/ZEukNBNeAfyYF9b/RUlaAFsokySRtiwcUVNGFjFg2qcDYVIH6hm06x44cKxsrVaHONPfiFypsb7k+6OEmSPlOyAeb+BPIrqXriVly4gruhMablyd3m/NIyw5+vQ9uednKvKWpWs9bXYC07IOVBVXYS6Ug5nZOC+E0RKKKKyE1qxiHYtPq63nyoSdx4LR3s7iuNLLVg2ZTvF7Jw7f+W+AJ0aRCi1TpIAXQdO4Bir6++XdXhfU2/7JWIY9zx5wj4rZPfR/5il0o7NTZxCpi0Rc7kkot8TCTEV86dnjMxsWogZiBHdGtbD5uqPSRX5wt+9QM5fmCIDdnr5YLKCbogMU8BUHdbUBHh+WIDl374zScgMYFpX60D1mAbr5gLAFtnx2eWjaD7xacWpEV97zuhHo/FI5v4FZblk2aKBmlNLgAginWlR8X1c6saltCjhwBYXFhzsD80=
  - secure: XOknz70pZ/5IAhlcSJ029JUH3wJ2qS+itROp45guIwmpfDIN3GnDGPtOfPE2ZZfGBGkX5X8QVaiW2HuQFKjD5oJd9l7S2H+bn5T63DTzFmgUhSWg7ZJBromp9KP6DyfS1AIxDUDlma5I7djx16WnopiWd/6NkhJ+2I7fg33wTpfgWAdiwder40o7PWuDvt3/hYOX6eV7DbuA7Fhskp23zBwIGLT6ma+DXwc085fH3mF+VCAKXJaKCTxa2IvrgfB8Uij5H+pabe3sieemzvj8TAu0ox3OS2GJCbofRA9263c/DflYKgmTcJIDeWEQY0iClEiHi1nX3NpyrfnsGboQJZyO/fPopGvQsttVBVDN6YMHOLaKKcearR2W6nTQtYL3kkd0XwHUA8K7V2NNdiD6B2PKZQLfS2V1twFd9AtnI0EdjTsFCSoppWNmWoTsCJBb6klXVnUR+gjsJmp6qJRlkX9y8UldIEa35T0gaheihmOJKrDQ28g9p5srZvkCBAe+Vx4VXIvtgvK7eCkyz+zH3AnPHHlilVnmpepDXDNAGvWsZM9Mp2kvSSrnuZpnIZREEGf1dE4xbMNxM+p1YGypkwE9otJaDK7AC2KytsBBZUX4Hm5Gv4I59332hv9hmRdeigMOCxiIyvFxhrtWZnNp4ZFx60u9IA9Z2UwmK91qLMQ=
